export const SERVICES = [
  {
    id: "ai-automation-systems",
    no: "01",
    title: "AI Automation Systems",
    desc: "End-to-end pipelines that eliminate repetitive work - document processing, workflow orchestration, intelligent routing.",
    accent: "#660033",
    sticker: "/service-stickers/ai-automation-sys.png",
    features: [
      "End-to-end Workflow Automation",
      "Intelligent Document Processing",
      "Workflow Orchestration",
      "Intelligent Routing & Triage",
    ],
  },
  {
    id: "custom-ai-agents",
    no: "02",
    title: "Custom AI Agents",
    desc: "Purpose-built agents that reason, plan, and act. Customer service, research, sales qualification, internal ops.",
    accent: "#EFBF04",
    sticker: "/service-stickers/custom-ai-agents.png",
    features: [
      "Customer Service Agents",
      "Research & Sales Qualification",
      "Internal Ops Automation",
      "Multi-step Agent Workflows",
    ],
  },
  {
    id: "llm-integration-fine-tuning",
    no: "03",
    title: "LLM Integration & Fine-Tuning",
    desc: "RAG pipelines, structured outputs, tool use, domain fine-tuning. Connecting language models to your business context.",
    accent: "#660033",
    sticker: "/service-stickers/llm-integration-finetune.png",
    features: [
      "RAG Pipeline Development",
      "Structured Output & Tool Use",
      "Domain Fine-Tuning",
      "Business Context Integration",
    ],
  },
  {
    id: "ai-strategy-consulting",
    no: "04",
    title: "AI Strategy & Consulting",
    desc: "Clarity before code. Whether evaluating a use-case or knee-deep in a failing build - honest technical guidance.",
    accent: "#EFBF04",
    sticker: "/service-stickers/ai-strategy-consulting.png",
    features: [
      "Use-case Evaluation",
      "Technical Architecture Review",
      "Build vs. Buy Analysis",
      "Honest Technical Guidance",
    ],
  },
  {
    id: "voice-ai-realtime-agents",
    no: "05",
    title: "Voice AI & Realtime Agents",
    desc: "Natural-sounding phone agents, voice interfaces, and realtime conversation systems - built on Realtime API, ElevenLabs, and Whisper.",
    accent: "#660033",
    sticker: "/service-stickers/voice-realtime-agents.png",
    features: [
      "Phone Agent Development",
      "Voice Interface Design",
      "Realtime Conversation Systems",
      "OpenAI Realtime API / ElevenLabs",
    ],
  },
  {
    id: "rag-knowledge-systems",
    no: "06",
    title: "RAG & Knowledge Systems",
    desc: "Turn documents, wikis, and databases into intelligent Q&A engines. Enterprise search, onboarding bots, and always-accurate knowledge bases.",
    accent: "#EFBF04",
    sticker: "/service-stickers/rag-knowledge-sys.png",
    features: [
      "Enterprise Search",
      "Document Q&A Engines",
      "Onboarding & Support Bots",
      "Knowledge Base Automation",
    ],
  },
  {
    id: "ai-content-seo-pipelines",
    no: "07",
    title: "AI Content & SEO Pipelines",
    desc: "Automated content at scale - product descriptions, SEO articles, social posts, email sequences. Consistent brand voice, zero manual effort.",
    accent: "#660033",
    sticker: "/service-stickers/ai-content-seo.png",
    features: [
      "Product Description Generation",
      "SEO Article Automation",
      "Email & Social Sequences",
      "Consistent Brand Voice",
    ],
  },
  {
    id: "computer-vision-multimodal-ai",
    no: "08",
    title: "Computer Vision & Multimodal AI",
    desc: "Image analysis, document OCR, visual defect detection, and video understanding. Turning pixels into structured, actionable data.",
    accent: "#EFBF04",
    sticker: "/service-stickers/computer-vision-multimodal.png",
    features: [
      "Image Analysis & OCR",
      "Visual Defect Detection",
      "Video Understanding",
      "Structured Data from Pixels",
    ],
  },
];
