const kraftedScreenshot = (file, title, alt) => ({
  src: `/work-media/krafted/${file}.jpg`,
  title,
  alt,
})

const mintfitScreenshot = (file, title, alt) => ({
  src: `/work-media/mintfit/${file}.jpg`,
  title,
  alt,
})

export const WORK_GALLERIES = {
  "krafted-ai-shopify-app": {
    eyebrow: "Product screens",
    title: "Krafted in Shopify",
    description:
      "The embedded application, page-generation flow, store controls, and final product-page output.",
    screenshots: [
      kraftedScreenshot(
        "01-krafted-launcher",
        "Product launcher",
        "Krafted embedded Shopify application showing the product-page generation launcher."
      ),
      kraftedScreenshot(
        "02-page-builder",
        "Page builder",
        "Krafted page builder with generated product sections inside Shopify."
      ),
      kraftedScreenshot(
        "03-generated-page",
        "Generated page",
        "Shopify product-page preview generated by Krafted."
      ),
      kraftedScreenshot(
        "04-krafted-settings",
        "Store setup",
        "Krafted store configuration and setup screen."
      ),
      kraftedScreenshot(
        "05-krafted-flow",
        "Generation flow",
        "Krafted workflow showing page-generation progress and controls."
      ),
      kraftedScreenshot(
        "06-admin-dashboard",
        "Admin dashboard",
        "Krafted administration dashboard for stores and generation configuration."
      ),
      kraftedScreenshot(
        "07-admin-controls",
        "Admin controls",
        "Krafted administration controls for application content and settings."
      ),
      kraftedScreenshot(
        "08-volume-offer",
        "Volume offer editor",
        "Volume-offer editor connected to the Krafted product-page workflow."
      ),
      kraftedScreenshot(
        "09-product-photos",
        "AI product photos",
        "AI product-photo generation screen in the Krafted workflow."
      ),
      kraftedScreenshot(
        "10-bundle-offers",
        "Bundle offers",
        "Bundle-offer interface used in generated Shopify product pages."
      ),
      kraftedScreenshot(
        "11-page-builder-plus",
        "Shopify Plus builder",
        "Shopify Plus page builder displaying generated Krafted content."
      ),
      kraftedScreenshot(
        "12-page-variant",
        "Page variant",
        "Alternative generated product-page variant in the Shopify page builder."
      ),
      kraftedScreenshot(
        "13-page-final",
        "Final page view",
        "Final generated Shopify product page."
      ),
    ],
  },
  "mintfit-ai-coaching": {
    eyebrow: "Product screens",
    title: "MintFit coaching workspace",
    description:
      "The connected client record, assessment workflow, AI assistance, program generation, and coach review experience.",
    screenshots: [
      mintfitScreenshot(
        "01-client-profile",
        "Client profile",
        "MintFit client profile with coaching context and assessment data."
      ),
      mintfitScreenshot(
        "02-program-builder",
        "Program builder",
        "MintFit program builder for creating a client training plan."
      ),
      mintfitScreenshot(
        "03-dashboard",
        "Coach dashboard",
        "MintFit coach dashboard with client and workflow information."
      ),
      mintfitScreenshot(
        "04-client-list",
        "Client list",
        "MintFit client list for browsing and opening coaching records."
      ),
      mintfitScreenshot(
        "05-assessments",
        "Assessments",
        "MintFit assessment workflow with client fitness measurements."
      ),
      mintfitScreenshot(
        "06-ai-chat",
        "AI assistant",
        "MintFit AI assistant grounded in client and coaching context."
      ),
      mintfitScreenshot(
        "07-plan-output",
        "Plan output",
        "Workout plan generated inside the MintFit coach workspace."
      ),
      mintfitScreenshot(
        "08-review-state",
        "Review state",
        "MintFit review screen for checking and editing generated recommendations."
      ),
    ],
  },
}

export function getWorkGallery(slug) {
  return WORK_GALLERIES[slug] || null
}
